// Base de datos de tarjetas (Mapeada desde Excel)
const cardsData = {
    1: { name: "Battery Park", url: "https://www.youtube.com/watch?v=XzNQRGhs6Tk" },
    2: { name: "Wall Street", url: "https://www.youtube.com/watch?v=ZumUXhuf9UQ" },
    3: { name: "Seaport", url: "https://www.youtube.com/watch?v=uKK4uULTEm0" },
    4: { name: "Zona Cero", url: "https://www.youtube.com/watch?v=-hQ6c710pYg&t=1s" },
    5: { name: "City Hall", url: "https://www.youtube.com/watch?v=zHumJtg_jPs" },
    6: { name: "Puente de Brooklyn", url: "https://www.youtube.com/watch?v=UYCwdSjW2dU" },
    7: { name: "Lower East Side 1", url: "https://www.youtube.com/watch?v=sK5JZIt8zA8" },
    8: { name: "Lower East Side 2", url: "https://www.youtube.com/watch?v=rfVbl8BHSNg&t=1s" },
    9: { name: "Nolita", url: "https://www.youtube.com/watch?v=ivRJKQF5c4M" },
    10: { name: "Little Italy", url: "https://www.youtube.com/watch?v=LnRD7BFJBKg" },
    11: { name: "Chinatown", url: "https://www.youtube.com/watch?v=Le7ielqjwHY" },
    12: { name: "Soho", url: "https://www.youtube.com/watch?v=ELpqbUiTSBg" },
    13: { name: "Tribeca", url: "https://www.youtube.com/watch?v=8QvLnSuhFyU" },
    14: { name: "NoHo", url: "https://www.youtube.com/watch?v=5j6F6uJY2JI" },
    15: { name: "Greenwich 1", url: "https://www.youtube.com/watch?v=iz7Fns3k-yY" },
    16: { name: "Greenwich 2", url: "https://www.youtube.com/watch?v=jyz_5HPfILQ" },
    17: { name: "Greenwich 3", url: "https://www.youtube.com/watch?v=GvhN8fhespE" },
    18: { name: "Midtown Sur", url: "https://www.youtube.com/watch?v=Au7wuybuUQY" },
    19: { name: "Hudson Yards", url: "https://www.youtube.com/watch?v=HPBA7m8NqHg" },
    20: { name: "The High Line", url: "https://www.youtube.com/watch?v=7xFDZRBPf80" },
    21: { name: "Chelsea 1", url: "https://www.youtube.com/watch?v=tCRIMVr-YjI" },
    22: { name: "Chelsea 2 y Meatpacking", url: "https://www.youtube.com/watch?v=VrZm7VY8qy0" },
    23: { name: "Midtown", url: "https://www.youtube.com/watch?v=wFgQdvEuJBM" },
    24: { name: "Rockefeller Center", url: "https://www.youtube.com/watch?v=0kkVdwfPpK4" },
    25: { name: "Times Square", url: "https://www.youtube.com/watch?v=4yPyyWA7Cas" },
    26: { name: "Midtown West", url: "https://www.youtube.com/watch?v=dnp89WrQ34k" },
    27: { name: "Midtown East", url: "https://www.youtube.com/watch?v=Jz_jdYPUTuU" },
    28: { name: "Upper East Side Sur", url: "https://www.youtube.com/watch?v=jmSqAYb3Zm8" },
    29: { name: "Upper East Side Norte", url: "https://www.youtube.com/watch?v=2m388O8x8y0" },
    30: { name: "Roosevelt Island", url: "https://www.youtube.com/watch?v=v6kSpehu6Xk" },
    31: { name: "Central Park Sur", url: "https://www.youtube.com/watch?v=9eoEPbs2lmA" },
    32: { name: "Central Park zona centro", url: "https://www.youtube.com/watch?v=MZAzQDyYGks" },
    33: { name: "Central Park Norte", url: "https://www.youtube.com/watch?v=08GTobNzXqE" },
    34: { name: "Upper West Side Sur", url: "https://www.youtube.com/watch?v=ZLDY8TvGUmY" },
    35: { name: "Upper West Side Norte", url: "https://www.youtube.com/watch?v=2m388O8x8y0" },
    36: { name: "Harlem", url: "https://www.youtube.com/watch?v=cmiYKOKCBhQ" }, 
    37: { name: "Morningside Heights", url: "https://www.youtube.com/watch?v=0zKY4psksyM" },
    38: { name: "Fort Tryon", url: "https://www.youtube.com/watch?v=kmYLcPdqOJo" },
    39: { name: "Estatua de la Libertad y Ellis Island", url: "https://www.youtube.com/watch?v=K0WIXR7KnOM" },
    40: { name: "DUMBO", url: "https://www.youtube.com/watch?v=IEP2v4_WSxc" },
    41: { name: "Brooklyn Heights", url: "https://www.youtube.com/watch?v=Pyps3R2V9vk" },
    42: { name: "Prospect Park este", url: "https://www.youtube.com/watch?v=VEYpLf7XwsU" },
    43: { name: "Prospect Park oeste", url: "https://www.youtube.com/watch?v=FrNv_9MJ3y4" },
    44: { name: "Bushwick", url: "https://www.youtube.com/watch?v=0i70bAU8DyE" },
    45: { name: "Williamsburg zona 1", url: "https://www.youtube.com/watch?v=4mPlVuru6SI" },
    46: { name: "Williamsburg zona 2", url: "https://www.youtube.com/watch?v=FoxW03m9zec" },
    47: { name: "Governors Island", url: "https://www.youtube.com/watch?v=Ox4EYJPID6o" },
    48: { name: "Dycker Heights", url: "https://www.youtube.com/watch?v=JccZoH0QgTo" },
    49: { name: "Coney Island", url: "https://www.youtube.com/watch?v=GHcRBQCxbSs" },
    50: { name: "Hoboken", url: "https://www.youtube.com/watch?v=Z1C-BPjfwMs" },
    51: { name: "Jersey City", url: "https://www.youtube.com/watch?v=mrK0dQyvUhA" },
    52: { name: "Portada 1", url: "#" },
    53: { name: "Índice 1", url: "#" },
    54: { name: "Índice 2", url: "#" },
    55: { name: "Portada 2", url: "#" },
    56: { name: "Seguro IATI", url: "#" }
};